from BaseClasses import Item, ItemClassification
from typing import NamedTuple, TYPE_CHECKING, Dict

if TYPE_CHECKING:
    from . import ChronoGearWorld

class CGItem(Item):
    game = "Chrono Gear"

class CGItemData(NamedTuple):
    id: int
    classification: ItemClassification
    max_quantity: int = 1

item_table: Dict[str, CGItemData] = {
    "Golden Gear": CGItemData(2001, ItemClassification.progression_skip_balancing, 35),
    "Laplus' Shackle": CGItemData(2101, ItemClassification.progression, 5),

    "Thread of Time - Time Page 1": CGItemData(2200, ItemClassification.progression_deprioritized_skip_balancing, 5),
    "Thread of Time - Time Page 2": CGItemData(2201, ItemClassification.progression_deprioritized_skip_balancing, 5),
    "Thread of Time - Time Page 3": CGItemData(2202, ItemClassification.progression_deprioritized_skip_balancing, 13),
    "Thread of Time - Space Page 1": CGItemData(2220, ItemClassification.progression_deprioritized_skip_balancing, 4),
    "Thread of Time - Sapce Page 2": CGItemData(2221, ItemClassification.progression_deprioritized_skip_balancing, 4),
    "Thread of Time - Nature": CGItemData(2210, ItemClassification.progression_deprioritized_skip_balancing, 4),
    "Thread of Time - Civilization": CGItemData(2230, ItemClassification.progression_deprioritized_skip_balancing, 7),
    "Thread of Time - Chaos": CGItemData(2240, ItemClassification.progression_deprioritized_skip_balancing, 9),

    "Chrono Gear": CGItemData(2400, ItemClassification.progression),

    "CD - Chrono Gear": CGItemData(2301, ItemClassification.filler),
    "CD - Her Time is Now (Intro Mix)": CGItemData(2302, ItemClassification.filler),
    "CD - Take Your Time": CGItemData(2303, ItemClassification.filler),
    "CD - Daydream (Tutorial Mix)": CGItemData(2304, ItemClassification.filler),
    "CD - A Beginning": CGItemData(2305, ItemClassification.filler),
    "CD - Bad Dream": CGItemData(2306, ItemClassification.filler),
    "CD - Separation": CGItemData(2307, ItemClassification.filler),
    "CD - Doorway to Nowhere": CGItemData(2308, ItemClassification.filler),
    "CD - Eternal Ambition": CGItemData(2309, ItemClassification.filler),
    "CD - Victory Theme": CGItemData(2310, ItemClassification.filler),
    "CD - World Map": CGItemData(2311, ItemClassification.filler),
    "CD - Bell Town": CGItemData(2312, ItemClassification.filler),
    "CD - Bell Town Under": CGItemData(2313, ItemClassification.filler),
    "CD - Unlucky Steps": CGItemData(2314, ItemClassification.filler),
    "CD - Carnival Railway": CGItemData(2315, ItemClassification.filler),
    "CD - Sands of Time": CGItemData(2316, ItemClassification.filler),
    "CD - Jewel Cyclone": CGItemData(2317, ItemClassification.filler),
    "CD - Jouya Repaint (Boss Mix)": CGItemData(2318, ItemClassification.filler),
    "CD - Jouya Repaint (Talk Mix)": CGItemData(2319, ItemClassification.filler),
    "CD - Cutscene - Council Meeting": CGItemData(2320, ItemClassification.filler),
    "CD - Galaxy Gourmet": CGItemData(2321, ItemClassification.filler),
    "CD - Sana's Theme": CGItemData(2322, ItemClassification.filler),
    "CD - Starship ID": CGItemData(2323, ItemClassification.filler),
    "CD - Cutscene - Space Traffic": CGItemData(2324, ItemClassification.filler),
    "CD - Marine's Theme": CGItemData(2325, ItemClassification.filler),
    "CD - Battleship Aquamarine": CGItemData(2326, ItemClassification.filler),
    "CD - Bare Your Teeth": CGItemData(2327, ItemClassification.filler),
    "CD - Ahoy?": CGItemData(2328, ItemClassification.filler),
    "CD - Hoshinova Castle (Outer)": CGItemData(2329, ItemClassification.filler),
    "CD - Hoshinova Castle": CGItemData(2330, ItemClassification.filler),
    "CD - Alter Laplus Thoughts": CGItemData(2331, ItemClassification.filler),
    "CD - The World Tree (Spring)": CGItemData(2332, ItemClassification.filler),
    "CD - The World Tree (Summer)": CGItemData(2333, ItemClassification.filler),
    "CD - The World Tree (Autumn)": CGItemData(2334, ItemClassification.filler),
    "CD - The World Tree (Winter)": CGItemData(2335, ItemClassification.filler),
    "CD - Magic Resort": CGItemData(2336, ItemClassification.filler),
    "CD - Teatime": CGItemData(2337, ItemClassification.filler),
    "CD - Sky Tops": CGItemData(2338, ItemClassification.filler),
    "CD - Tidal Camp": CGItemData(2339, ItemClassification.filler),
    "CD - Pekora's Theme": CGItemData(2340, ItemClassification.filler),
    "CD - Depths of Atlantis": CGItemData(2341, ItemClassification.filler),
    "CD - Wrath of Nature": CGItemData(2342, ItemClassification.filler),
    "CD - Between Worlds": CGItemData(2343, ItemClassification.filler),
    "CD - Alter Laplus Theme": CGItemData(2344, ItemClassification.filler),
    "CD - Dear Highest Death": CGItemData(2345, ItemClassification.filler),
    "CD - Dear Highest Death - Try Again": CGItemData(2346, ItemClassification.filler),
    "CD - Reflection in Time": CGItemData(2347, ItemClassification.filler),
    "CD - Town Square": CGItemData(2348, ItemClassification.filler),
    "CD - Castle Road": CGItemData(2349, ItemClassification.filler),
    "CD - Castle Siege": CGItemData(2350, ItemClassification.filler),
    "CD - The Maze": CGItemData(2351, ItemClassification.filler),
    "CD - Cursed Lands": CGItemData(2352, ItemClassification.filler),
    "CD - Magitech Forge": CGItemData(2353, ItemClassification.filler),
    "CD - -little bit-": CGItemData(2354, ItemClassification.filler),
    "CD - Baelz's Theme": CGItemData(2355, ItemClassification.filler),
    "CD - Highway of Dreams": CGItemData(2356, ItemClassification.filler),
    "CD - The Funzone": CGItemData(2357, ItemClassification.filler),
    "CD - Amelia's Theme": CGItemData(2358, ItemClassification.filler),
    "CD - Ducky God Arcade": CGItemData(2359, ItemClassification.filler),
    "CD - Symphonic Gallery": CGItemData(2360, ItemClassification.filler),
    "CD - Kiara's Theme": CGItemData(2361, ItemClassification.filler),
    "CD - KFP Stadium": CGItemData(2362, ItemClassification.filler),
    "CD - Hurry Up": CGItemData(2363, ItemClassification.filler),
    "CD - On the Case": CGItemData(2364, ItemClassification.filler),
    "CD - Candle in the Dark": CGItemData(2365, ItemClassification.filler),
    "CD - Alter Bell Town": CGItemData(2366, ItemClassification.filler),
    "CD - Alter Hoshinova Castle": CGItemData(2367, ItemClassification.filler),
    "CD - I Can't Reach You": CGItemData(2368, ItemClassification.filler),
    "CD - Alter World Tree": CGItemData(2369, ItemClassification.filler),
    "CD - Deep Cut": CGItemData(2370, ItemClassification.filler),
    "CD - Alter Castle Road": CGItemData(2371, ItemClassification.filler),
    "CD - Truth of Despair": CGItemData(2372, ItemClassification.filler),
    "CD - Hand in Hand": CGItemData(2373, ItemClassification.filler),
    "CD - Alter KFP Stadium": CGItemData(2374, ItemClassification.filler),
    "CD - Her Time is Now (Dark Nest)": CGItemData(2375, ItemClassification.filler),
    "CD - Tower of Darkness (Lobby)": CGItemData(2376, ItemClassification.filler),
    "CD - Tower of Darkness (Prelude)": CGItemData(2377, ItemClassification.filler),
    "CD - Tower of Darkness (Interior)": CGItemData(2378, ItemClassification.filler),
    "CD - Tower of Darkness (Exterior)": CGItemData(2379, ItemClassification.filler),
    "CD - Tower of Light": CGItemData(2380, ItemClassification.filler),
    "CD - My Decaying Heart": CGItemData(2381, ItemClassification.filler),
    "CD - Steel on Steel (Tower of Darknesss 3)": CGItemData(2382, ItemClassification.filler),
    "CD - Zero Seconds to Midnight": CGItemData(2383, ItemClassification.filler),
    "CD - IRyS's Theme": CGItemData(2384, ItemClassification.filler),
    "CD - Chrono Gear Launch Trailer": CGItemData(2385, ItemClassification.filler),
    "CD - Threads of Time": CGItemData(2386, ItemClassification.filler),
    "CD - Daydreaming in Darkness": CGItemData(2387, ItemClassification.filler),

    "Border Art - TimeRyS": CGItemData(2521, ItemClassification.filler),
    "Border Art - Amelia": CGItemData(2501, ItemClassification.filler),
    "Border Art - holoX": CGItemData(2510, ItemClassification.filler),
    "Border Art - IRyS": CGItemData(2509, ItemClassification.filler),
    "Border Art - Myth": CGItemData(2516, ItemClassification.filler),
    "Border Art - Fauna": CGItemData(2507, ItemClassification.filler),
    "Border Art - id:entity": CGItemData(2511, ItemClassification.filler),
    "Border Art - Ina": CGItemData(2508, ItemClassification.filler),
    "Border Art - Sana": CGItemData(2519, ItemClassification.filler),
    "Border Art - Souten ni Moyu": CGItemData(2520, ItemClassification.filler),
    "Border Art - Moona": CGItemData(2514, ItemClassification.filler),
    "Border Art - Mumei": CGItemData(2515, ItemClassification.filler),
    "Border Art - Calli": CGItemData(2506, ItemClassification.filler),
    "Border Art - Roboco-san": CGItemData(2518, ItemClassification.filler),
    "Border Art - Baelz": CGItemData(2503, ItemClassification.filler),
    "Border Art - Laplus": CGItemData(2513, ItemClassification.filler),
    "Border Art - Korone": CGItemData(2512, ItemClassification.filler),

    "Storming the Sanctum": CGItemData(1101, ItemClassification.progression),
    "The Top of Bell Tower": CGItemData(1102, ItemClassification.progression),
    "The Battle of Bell Town": CGItemData(1104, ItemClassification.progression),
    "The PolPol Express": CGItemData(1105, ItemClassification.progression),
    "The Gravity of Time": CGItemData(1107, ItemClassification.progression),
    "The Shattered Keep": CGItemData(1109, ItemClassification.progression),
    "Call to Nature": CGItemData(1111, ItemClassification.progression),
    "Autumn Harvest": CGItemData(1112, ItemClassification.progression),
    "Wrath of Nature": CGItemData(1114, ItemClassification.progression),
    "The Floating Islands": CGItemData(1115, ItemClassification.progression),
    "Riding the Waves": CGItemData(1117, ItemClassification.progression),
    "Chloe's Beach Race": CGItemData(1118, ItemClassification.progression),
    "Rebuilding the Lost City": CGItemData(1119, ItemClassification.progression),
    "The Great Space Bake": CGItemData(1121, ItemClassification.progression),
    "The Houshou Pirates": CGItemData(1123, ItemClassification.progression),
    "Luknight of Darkness": CGItemData(1124, ItemClassification.progression),
    "Ganmo's Grand Finale": CGItemData(1126, ItemClassification.progression),
    "The Road to Civilization": CGItemData(1127, ItemClassification.progression),
    "Roboco Strikes Back": CGItemData(1128, ItemClassification.progression),
    "Path of Memories": CGItemData(1129, ItemClassification.progression),
    "A Head Start": CGItemData(1131, ItemClassification.progression),
    "The War Mind": CGItemData(1133, ItemClassification.progression),
    "Caravan of Darkness": CGItemData(1135, ItemClassification.progression),
    "Overclocking the Arcade": CGItemData(1136, ItemClassification.progression),
    "Song of Light and Darkness": CGItemData(1138, ItemClassification.progression),
    "Case Closed": CGItemData(1139, ItemClassification.progression),
    "The KFP Games": CGItemData(1140, ItemClassification.progression),
    "Another Time Traveler?": CGItemData(1141, ItemClassification.progression),
    "The Space Between Worlds": CGItemData(1142, ItemClassification.progression),
    "Solitude": CGItemData(1143, ItemClassification.progression),
    "Entropy": CGItemData(1144, ItemClassification.progression),
    "Gloom": CGItemData(1145, ItemClassification.progression),
    "Despair": CGItemData(1146, ItemClassification.progression),
    "Hope": CGItemData(1147, ItemClassification.progression),
    "Her Time is Now": CGItemData(1148, ItemClassification.progression),
    "The Final Ascent": CGItemData(1149, ItemClassification.progression),
    "Steel on Steel": CGItemData(1150, ItemClassification.progression),
    "Defending the Sanctum": CGItemData(1151, ItemClassification.progression),
    "Eternity Sanctum": CGItemData(1152, ItemClassification.progression),
    "The Starship ID": CGItemData(1153, ItemClassification.progression),
    "Magic Resort": CGItemData(1154, ItemClassification.progression),
    "The Funzone": CGItemData(1155, ItemClassification.progression),
    "Castle Town": CGItemData(1156, ItemClassification.progression),
    "The Bunker": CGItemData(1157, ItemClassification.progression),
    "The Ancient Ones": CGItemData(1158, ItemClassification.progression),
    "The Way Home": CGItemData(1159, ItemClassification.progression),
    "Zero Seconds to Midnight": CGItemData(1161, ItemClassification.progression),
}

world_unlock_items: Dict[str, CGItemData] = {
    "World of Time": CGItemData(1200, ItemClassification.progression),
    "World of Nature": CGItemData(1201, ItemClassification.progression),
    "World of Space": CGItemData(1202, ItemClassification.progression),
    "World of Civilzation": CGItemData(1203, ItemClassification.progression),
    "World of Chaos": CGItemData(1204, ItemClassification.progression),
    "World of Darkness": CGItemData(1205, ItemClassification.progression),
    "Alter Timeline": CGItemData(1206, ItemClassification.progression),
}

filler_items: Dict[str, CGItemData] = {
    "CD - Chrono Gear": CGItemData(2301, ItemClassification.filler),
    "CD - Her Time is Now (Intro Mix)": CGItemData(2302, ItemClassification.filler),
    "CD - Take Your Time": CGItemData(2303, ItemClassification.filler),
    "CD - Daydream (Tutorial Mix)": CGItemData(2304, ItemClassification.filler),
    "CD - A Beginning": CGItemData(2305, ItemClassification.filler),
    "CD - Bad Dream": CGItemData(2306, ItemClassification.filler),
    "CD - Separation": CGItemData(2307, ItemClassification.filler),
    "CD - Doorway to Nowhere": CGItemData(2308, ItemClassification.filler),
    "CD - Eternal Ambition": CGItemData(2309, ItemClassification.filler),
    "CD - Victory Theme": CGItemData(2310, ItemClassification.filler),
    "CD - World Map": CGItemData(2311, ItemClassification.filler),
    "CD - Bell Town": CGItemData(2312, ItemClassification.filler),
    "CD - Bell Town Under": CGItemData(2313, ItemClassification.filler),
    "CD - Unlucky Steps": CGItemData(2314, ItemClassification.filler),
    "CD - Carnival Railway": CGItemData(2315, ItemClassification.filler),
    "CD - Sands of Time": CGItemData(2316, ItemClassification.filler),
    "CD - Jewel Cyclone": CGItemData(2317, ItemClassification.filler),
    "CD - Jouya Repaint (Boss Mix)": CGItemData(2318, ItemClassification.filler),
    "CD - Jouya Repaint (Talk Mix)": CGItemData(2319, ItemClassification.filler),
    "CD - Cutscene - Council Meeting": CGItemData(2320, ItemClassification.filler),
    "CD - Galaxy Gourmet": CGItemData(2321, ItemClassification.filler),
    "CD - Sana's Theme": CGItemData(2322, ItemClassification.filler),
    "CD - Starship ID": CGItemData(2323, ItemClassification.filler),
    "CD - Cutscene - Space Traffic": CGItemData(2324, ItemClassification.filler),
    "CD - Marine's Theme": CGItemData(2325, ItemClassification.filler),
    "CD - Battleship Aquamarine": CGItemData(2326, ItemClassification.filler),
    "CD - Bare Your Teeth": CGItemData(2327, ItemClassification.filler),
    "CD - Ahoy?": CGItemData(2328, ItemClassification.filler),
    "CD - Hoshinova Castle (Outer)": CGItemData(2329, ItemClassification.filler),
    "CD - Hoshinova Castle": CGItemData(2330, ItemClassification.filler),
    "CD - Alter Laplus Thoughts": CGItemData(2331, ItemClassification.filler),
    "CD - The World Tree (Spring)": CGItemData(2332, ItemClassification.filler),
    "CD - The World Tree (Summer)": CGItemData(2333, ItemClassification.filler),
    "CD - The World Tree (Autumn)": CGItemData(2334, ItemClassification.filler),
    "CD - The World Tree (Winter)": CGItemData(2335, ItemClassification.filler),
    "CD - Magic Resort": CGItemData(2336, ItemClassification.filler),
    "CD - Teatime": CGItemData(2337, ItemClassification.filler),
    "CD - Sky Tops": CGItemData(2338, ItemClassification.filler),
    "CD - Tidal Camp": CGItemData(2339, ItemClassification.filler),
    "CD - Pekora's Theme": CGItemData(2340, ItemClassification.filler),
    "CD - Depths of Atlantis": CGItemData(2341, ItemClassification.filler),
    "CD - Wrath of Nature": CGItemData(2342, ItemClassification.filler),
    "CD - Between Worlds": CGItemData(2343, ItemClassification.filler),
    "CD - Alter Laplus Theme": CGItemData(2344, ItemClassification.filler),
    "CD - Dear Highest Death": CGItemData(2345, ItemClassification.filler),
    "CD - Dear Highest Death - Try Again": CGItemData(2346, ItemClassification.filler),
    "CD - Reflection in Time": CGItemData(2347, ItemClassification.filler),
    "CD - Town Square": CGItemData(2348, ItemClassification.filler),
    "CD - Castle Road": CGItemData(2349, ItemClassification.filler),
    "CD - Castle Siege": CGItemData(2350, ItemClassification.filler),
    "CD - The Maze": CGItemData(2351, ItemClassification.filler),
    "CD - Cursed Lands": CGItemData(2352, ItemClassification.filler),
    "CD - Magitech Forge": CGItemData(2353, ItemClassification.filler),
    "CD - -little bit-": CGItemData(2354, ItemClassification.filler),
    "CD - Baelz's Theme": CGItemData(2355, ItemClassification.filler),
    "CD - Highway of Dreams": CGItemData(2356, ItemClassification.filler),
    "CD - The Funzone": CGItemData(2357, ItemClassification.filler),
    "CD - Amelia's Theme": CGItemData(2358, ItemClassification.filler),
    "CD - Ducky God Arcade": CGItemData(2359, ItemClassification.filler),
    "CD - Symphonic Gallery": CGItemData(2360, ItemClassification.filler),
    "CD - Kiara's Theme": CGItemData(2361, ItemClassification.filler),
    "CD - KFP Stadium": CGItemData(2362, ItemClassification.filler),
    "CD - Hurry Up": CGItemData(2363, ItemClassification.filler),
    "CD - On the Case": CGItemData(2364, ItemClassification.filler),
    "CD - Candle in the Dark": CGItemData(2365, ItemClassification.filler),
    "CD - Alter Bell Town": CGItemData(2366, ItemClassification.filler),
    "CD - Alter Hoshinova Castle": CGItemData(2367, ItemClassification.filler),
    "CD - I Can't Reach You": CGItemData(2368, ItemClassification.filler),
    "CD - Alter World Tree": CGItemData(2369, ItemClassification.filler),
    "CD - Deep Cut": CGItemData(2370, ItemClassification.filler),
    "CD - Alter Castle Road": CGItemData(2371, ItemClassification.filler),
    "CD - Truth of Despair": CGItemData(2372, ItemClassification.filler),
    "CD - Hand in Hand": CGItemData(2373, ItemClassification.filler),
    "CD - Alter KFP Stadium": CGItemData(2374, ItemClassification.filler),
    "CD - Her Time is Now (Dark Nest)": CGItemData(2375, ItemClassification.filler),
    "CD - Tower of Darkness (Lobby)": CGItemData(2376, ItemClassification.filler),
    "CD - Tower of Darkness (Prelude)": CGItemData(2377, ItemClassification.filler),
    "CD - Tower of Darkness (Interior)": CGItemData(2378, ItemClassification.filler),
    "CD - Tower of Darkness (Exterior)": CGItemData(2379, ItemClassification.filler),
    "CD - Tower of Light": CGItemData(2380, ItemClassification.filler),
    "CD - My Decaying Heart": CGItemData(2381, ItemClassification.filler),
    "CD - Steel on Steel (Tower of Darknesss 3)": CGItemData(2382, ItemClassification.filler),
    "CD - Zero Seconds to Midnight": CGItemData(2383, ItemClassification.filler),
    "CD - IRyS's Theme": CGItemData(2384, ItemClassification.filler),
    "CD - Chrono Gear Launch Trailer": CGItemData(2385, ItemClassification.filler),
    "CD - Threads of Time": CGItemData(2386, ItemClassification.filler),
    "CD - Daydreaming in Darkness": CGItemData(2387, ItemClassification.filler),

    "Border Art - TimeRyS": CGItemData(2521, ItemClassification.filler),
    "Border Art - Amelia": CGItemData(2501, ItemClassification.filler),
    "Border Art - holoX": CGItemData(2510, ItemClassification.filler),
    "Border Art - IRyS": CGItemData(2509, ItemClassification.filler),
    "Border Art - Myth": CGItemData(2516, ItemClassification.filler),
    "Border Art - Fauna": CGItemData(2507, ItemClassification.filler),
    "Border Art - id:entity": CGItemData(2511, ItemClassification.filler),
    "Border Art - Ina": CGItemData(2508, ItemClassification.filler),
    "Border Art - Sana": CGItemData(2519, ItemClassification.filler),
    "Border Art - Souten ni Moyu": CGItemData(2520, ItemClassification.filler),
    "Border Art - Moona": CGItemData(2514, ItemClassification.filler),
    "Border Art - Mumei": CGItemData(2515, ItemClassification.filler),
    "Border Art - Calli": CGItemData(2506, ItemClassification.filler),
    "Border Art - Roboco-san": CGItemData(2518, ItemClassification.filler),
    "Border Art - Baelz": CGItemData(2503, ItemClassification.filler),
    "Border Art - Laplus": CGItemData(2513, ItemClassification.filler),
    "Border Art - Korone": CGItemData(2512, ItemClassification.filler),
}

def generate_item(world: ChronoGearWorld, name: str) -> Item:
    item = CGItem(name, item_table[name].classification, item_table[name].id, world.player)

    return item

def generate_all_items(world: ChronoGearWorld):
    itempool: list[Item] = []
    for name, data in item_table:
        itempool += world.create_item(name)
    
    if world.options.world_unlock_mode == 1:
        for name, data in world_unlock_items:
            itempool += world.create_item(name)
    
    item_count = len(itempool)
    unfilled_locations = len(world.multiworld.get_unfilled_locations(world.player))
    #This should always be 0, but just making sure
    needed_filler = unfilled_locations - item_count
    itempool += [world.create_filler() for _ in range(needed_filler)]

def get_filler_name(world: ChronoGearWorld) -> str:
    return filler_items.keys[world.random.randint(0, len(filler_items.keys) - 1)]

def get_items_for_mapping() -> Dict[str, CGItemData]:
    return item_table | world_unlock_items